language: php
php:
  - 5.5
  - 5.6

services:
  - memcached

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/codecept run unit